### ISSUE TITLE
Restriction on only training transformer layers?

### ISSUE THREAD

**Issue by bakszero** [nshepperd/gpt-2#12]
I see in the training code that: 
```

   if args.model_name == '345M':
        args.memory_saving_gradients = True
        args.only_train_transformer_layers = True
```
Why is the restriction imposed when finetuning for the 345M model? Am I missing something here?

**Comment by nshepperd** [comment]
I added this restriction because I had constant OOMs when trying to train all the layers due to the model size. But freezing the word embedding seems to save enough memory for it to fit in my 1080ti.
I figured that should not impact performance because the word embeddings should already be very well trained from the original model, and not need much adjustment.

**Comment by bakszero** [comment]
> I added this restriction because I had constant OOMs when trying to train all the layers due to the model size. But freezing the word embedding seems to save enough memory for it to fit in my 1080ti.
> I figured that should not impact performance because the word embeddings should already be very well trained from the original model, and not need much adjustment.

Sounds good. Is there multi-GPU support for the OOM error currently? I might have to use the 345M model and OOM is bound to happen I believe as you quoted. All in all, this is great work and kudos to you @nshepperd !

**Comment by XinyuDu** [comment]
> I added this restriction because I had constant OOMs when trying to train all the layers due to the model size. But freezing the word embedding seems to save enough memory for it to fit in my 1080ti.
> I figured that should not impact performance because the word embeddings should already be very well trained from the original model, and not need much adjustment.

Do we need to retrain the word embeddings if we train the Chinese model? THX.

**Comment by nshepperd** [comment]
Yes, quite probably you would benefit from retraining the word embeddings if you want to train a non-english model. You can do so if you set the optimizer to sgd instead of adam. See README.md for that. Possibly you also might want to build a new vocabulary/bpe entirely, but this repo doesn't have the tools for that.

No, I haven't updated the multi-gpu code in a while. I myself don't have multiple gpus, which makes it hard to test that part.

**Comment by bakszero** [comment]
> No, I haven't updated the multi-gpu code in a while. I myself don't have multiple gpus, which makes it hard to test that part.

Sure no problem, I might update and send in a pull request if I get time. Thanks.

**Comment by raaka1** [comment]
I can give access to DGX machine for testing, do let me know
